name: Hello World

on:
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: |
          echo "Hello world!"

  say_hello1:
    needs: say_hello
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: |
          echo "Hello world!"
