name: Matrix Port Conflict Demo
on: [push]

jobs:
  serve-web:
    name: Serve Web (instance ${{ matrix.instance }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: [1, 2]
    services:
      web:
        image: nginx:stable-alpine
        ports:
          - 8080:80
        options: >-
          --health-cmd="curl --fail http://localhost:80"
          --health-interval=2s
          --health-retries=5
    steps:
      - name: Probe nginx
        run: |
          echo "Instance ${{ matrix.instance }}"
          curl --fail http://localhost:8080
