name: Hello Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name?'
        required: true

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: |
          echo "Hello, ${{ github.event.inputs.name }}!"
