name: Use Secrets

on:
  workflow_dispatch:

env:
  SECRET_NAME: ${{ secrets.SECRET_NAME }}

jobs:
  say_hello2secret:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: |
          echo "Hello, ${{env.SECRET_NAME}}!"
